include ../../base.mk

# ------------------------------------------------------------------------------
# Example-specific configuration
# ------------------------------------------------------------------------------
RAW_PDB = ../1AF6_in_membrane.pdb

# PDB2SPN INPUTS
FF = $(BS_DATA_DIR)/forcefield/CAallresBaaden.ff
GRP =  $(BS_DATA_DIR)/reducerules/CAallresBaaden.grp
CUTOFF = 9.0
STIFFNESS = 30.0

# Prepare the input files for the simulation
prep : pdb2spn
