name: biospring
channels:
  - conda-forge
  - defaults
dependencies:
  - cmake
  - libnetcdf
  - netcdf-cxx4
  - pip
  - python==3.10.13
  - pdbfixer
  # Packages installed for tools/InteractivePlot.ipynb
  - ipykernel
  - pandas
  - conda-forge::jupyter-dash
  - conda-forge::ipywidgets
  - pyqt
  - pillow
