include ../../base.mk

# ------------------------------------------------------------------------------
# Example-specific configuration
# ------------------------------------------------------------------------------
RAW_PDB = ../1AF6_in_membrane.pdb

# PDB2SPN INPUTS
FF = $(BS_DATA_DIR)/martini/forcefield/martini_octanol.ff
GRP =  $(BS_DATA_DIR)/martini/reducerules/martini.grp
CUTOFF = 5.0
STIFFNESS = 30.0

# MARTINIZE TOOL
# INPUT: model_in_membrane.pdb (1BXW.pdb positioned in the membrane)
# OUTPUT: pdb2spn_input.pdb (PDB2SPN INPUT)
$(PDB2SPN_INPUT): $(RAW_PDB)
	@echo "Copy PDB input for Martinize"
	cp $(RAW_PDB) raw.pdb
	@echo "Run Martinize"
	docker run --rm -v $(PWD):/data $(IMAGE) \
    $(MARTINIZE) -f raw.pdb \
                 -x $(PDB2SPN_INPUT) \
                 -ff martini30b32 \
                 -resid input \
                 -ignh
	rm raw.pdb
	@read -p "Press enter to continue..." key
