include ../../base.mk

# ------------------------------------------------------------------------------
# Example-specific configuration
# ------------------------------------------------------------------------------
RAW_PDB = ../model_in_membrane.pdb

# PDB2SPN INPUTS
FF = $(BS_DATA_DIR)/forcefield/CAallresBaaden.ff
GRP =  $(BS_DATA_DIR)/reducerules/CAallresBaaden.grp
CUTOFF = 9.0
STIFFNESS = 30.0

$(PDB2SPN_INPUT): $(RAW_PDB)
	cp $(RAW_PDB) $(PDB2SPN_INPUT)
