include ../../base.mk

# ------------------------------------------------------------------------------
# Example-specific configuration
# ------------------------------------------------------------------------------
RAW_PDB = ../1AF6_in_membrane.pdb

# PDB2SPN INPUTS
FF = $(BS_DATA_DIR)/forcefield/amber.ff
GRP =  $(BS_DATA_DIR)/reducerules/amber.grp
CUTOFF = 5.0
STIFFNESS = 30.0

$(PDB2SPN_INPUT): $(RAW_PDB)
	cp $(RAW_PDB) $(PDB2SPN_INPUT)
