include ../../base.mk

# ------------------------------------------------------------------------------
# Example-specific configuration
# ------------------------------------------------------------------------------
RAW_PDB = ../model_in_membrane.pdb

# PDB2SPN INPUTS
FF = $(BS_DATA_DIR)/martini/forcefield/martini_octanol.ff
GRP =  $(BS_DATA_DIR)/martini/reducerules/martini.grp
CUTOFF = 5.0
STIFFNESS = 30.0

# Prepare the input files for the simulation
prep : martinize pause pdb2spn
