name: Build & Test

on:
  push:
  pull_request:
  release:
  workflow_call:


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y cmake libnetcdf-c++4-dev g++ libc++-dev libc++abi-dev

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Checkout MDDriver
        uses: actions/checkout@v4
        with:
          repository: LBT-CNRS/MDDriver
          ref: master
          path: mddriver-source

      - name: Compile MDDriver
        run: |
          cd mddriver-source
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/mddriver
          cmake --build build
          sudo cmake --install build

      - name: Checkout FreeSASA
        uses: actions/checkout@v4
        with:
          repository: mittinatten/freesasa
          ref: '2.1.2'
          path: freesasa-source

      - name: Compile FreeSASA
        run: |
          cd freesasa-source
          git submodule init
          git submodule update
          autoreconf -i
          ./configure --prefix /freesasa --disable-json --disable-xml
          make -j$(nproc) && sudo make install


      - name: Build BioSpring
        run: |
          cmake . -B build -DBUILD_TESTS=ON -DMDDRIVER_SUPPORT=ON -DMDDriver_DIR=/mddriver/share/cmake/ \
            -DFREESASA_SUPPORT=ON -DFREESASA_PREFIX=/freesasa
          make -C build -j$(nproc)

      - name: Test BioSpring
        run: make -C build test
